name: my_wit_wallet
description: myWitWallet allows you to send and receive Wit immediately. Bye bye synchronization!

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  msix: ^3.16.1
  test: ^1.21.4

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  bloc: ^8.0.3
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.7
  carousel_slider: ^4.1.1
  path_provider: ^2.0.1
  quiver: ^3.0.1
  another_flushbar: ^1.10.23
  dart_date: ^1.1.1
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  sembast: ^3.0.4
  encrypt: ^5.0.0
  equatable: ^2.0.3
  flutter_launcher_icons: 0.13.0
  sliding_up_panel: ^2.0.0+1
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  worker_manager: ^4.0.2
  toml: ^0.13.1
  decimal: 2.3.2
  witnet: 0.2.8
  table_calendar: ^3.0.3
  qr_flutter: ^4.0.0
  window_manager: ^0.3.2
  url_launcher: ^6.0.10
  flutter_dotenv: ^5.0.2
  date_format: ^2.0.5
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^3.2.0
  formz: ^0.4.1
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^2.0.5
  number_paginator: ^0.2.3
  local_auth: ^2.1.6

flutter_icons:
  android: true
  adaptive_icon_foreground: "assets/icon/adaptive-foreground.png"
  adaptive_icon_background: "assets/icon/adaptive-background.png"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"


flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/img/
    - assets/img/2x/
    - assets/img/3x/
    - .env

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Bold.ttf
          weight: 700

msix_config:
  display_name: myWitWallet
  publisher_display_name: Witnet Foundation
  publisher: CN=<REAL_CN>
  identity_name: WitnetFoundation.myWitWallet
  msix_version: 0.1.5.0
  logo_path: .\assets\icon\icon.png
  msstore_appId: 9PN09DKWPL57