name: witnet_wallet
description: Witnet Wallet

publish_to: 'none'

version: 0.0.1-dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.1.0
  get_it: ^7.2.0
  flutter_bloc: ^7.2.0
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.7
  path_provider: ^2.0.1
  flutter_svg: ^0.22.0
  quiver: ^3.0.1
  another_flushbar: ^1.10.23
  font_awesome_flutter: ^9.1.0
  intl: ^0.17.0
  sembast: ^3.0.4
  encrypt: ^5.0.0
  equatable: ^2.0.3

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  worker_manager: ^4.0.2
  toml: ^0.11.0


  witnet: 0.1.2-dev
  #witnet:
  #  path: ../witnet
  table_calendar: ^3.0.3
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.10
  flutter_dotenv: ^5.0.2


flutter:

  uses-material-design: true
  assets:
    - assets/img/
    - .env

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Sans-Regular.ttf
        - asset: assets/fonts/Nunito-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Sans-Bold.ttf
          weight: 700