name: witnet_wallet
description: Witnet Wallet

publish_to: 'none'

version: 0.0.1-dev

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  test: ^1.21.4

dependencies:
  flutter:
    sdk: flutter

  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  bloc: ^8.0.3
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.7
  carousel_slider: ^4.1.1
  path_provider: ^2.0.1
  quiver: ^3.0.1
  another_flushbar: ^1.10.23
  dart_date: ^1.1.1
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  sembast: ^3.0.4
  encrypt: ^5.0.0
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.9.2
  sliding_up_panel: ^2.0.0+1
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  worker_manager: ^4.0.2
  toml: ^0.13.1
  decimal: 2.3.2
  witnet: 0.2.2
  table_calendar: ^3.0.3
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.10
  flutter_dotenv: ^5.0.2
  date_format: ^2.0.5
  qr_code_scanner: ^1.0.1
  formz: ^0.4.1
  flutter_hooks: ^0.18.5+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/2x/
    - assets/img/3x/
    - .env

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Sans-Regular.ttf
        - asset: assets/fonts/Nunito-Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Sans-Bold.ttf
          weight: 700