name: my_wit_wallet
description: myWitWallet allows you to send and receive Wit immediately. Bye bye synchronization!

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  msix: ^3.16.1
  test: ^1.24.9

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.1.2
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.1
  carousel_slider: ^5.0.0
  quiver: ^3.2.1
  dart_date: ^1.3.2
  font_awesome_flutter: ^10.5.0
  intl: ^0.19.0
  sembast: ^3.4.9
  encrypt: ^5.0.3
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  sliding_up_panel: ^2.0.0+1
  decimal: 3.0.2
  witnet: 0.4.3
  path_provider: ^2.0.8
  permission_handler: ^11.0.1
  open_file: ^3.3.2
  qr_flutter: ^4.1.0
  window_manager: ^0.3.6
  url_launcher: ^6.1.14
  flutter_dotenv: ^5.1.0
  qr_code_scanner: ^1.0.1
  mobile_scanner: 5.1.1
  formz: ^0.7.0
  flutter_hooks: ^0.20.2
  flutter_svg: ^2.0.7
  number_paginator: ^0.4.0
  local_auth: ^2.3.0
  flutter_json_viewer: ^1.0.1
  updat: ^1.2.0+1
  logger: ^2.0.2+1
  pub_semver: ^2.1.4

flutter_icons:
  android: true
  adaptive_icon_foreground: "assets/icon/adaptive-foreground.png"
  adaptive_icon_background: "assets/icon/adaptive-background.png"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/img/
    - assets/img/2x/
    - assets/img/3x/
    - .env

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Bold.ttf
          weight: 700

msix_config:
  display_name: myWitWallet
  publisher_display_name: Witnet Foundation
  publisher: CN=<REAL_CN>
  identity_name: WitnetFoundation.myWitWallet
  msix_version: 1.2.1.0
  logo_path: .\assets\icon\icon.png
  msstore_appId: 9PN09DKWPL57